title: SEO
icon: cog
files: true
pages: false
fields:
  title:
    label: Título
    type:  text

  author:
    label: Autor
    type:  text
    icon: font
    width: 1/2
    placeholder: Empresa
    help: Nombre del autor

  seoimage:
    label: Share imagen (Rede Sociales)
    type:  image
    width: 1/2
    help: Imagen que aparece al compartir la URL de tu sitio web

  seodescription:
    label: Descripción
    type:  textarea
    placeholder: ¿Quiénes somos?
    help: Breve descripción sobre <strong>¿Quiénes somos?</strong> (50–300 characters.)

  seotags:
    label: keywords
    type:  tags
    help: Agregar el nombre de cada palabra separado por una <strong>coma (,)</strong>

  idgoogle:
    label: ID Google
    type:  text