title: Site
pages: default
fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description website
    type:  textarea

  keywords:
    label: Keys website
    type:  tags
    icon: keyboard-o
