title: Site
pages: default
fields:
  tab1:
    label: Social Media & SEO
    type: tabs
    icon: pie-chart

  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text
    icon: user
    width: 1/2

  seoimage:
    label: Share image
    type:  image
    width: 1/2

  seodescription:
    label: Description website
    type:  textarea
    help: Content description less than 200 characters

  seokeywords:
    label: Keys website
    type:  tags
    icon: keyboard-o

  tab2:
    label: Configure & Release
    type: tabs
    icon: plug

  versioncss:
    label: version CSS
    type:  text
    width: 1/3
    icon: css3

  versionplugins:
    label: version Plugins
    type:  text
    width: 1/3
    icon: jsfiddle

  versionmain:
    label: version Javascript
    type:  text
    width: 1/3
    icon: jsfiddle

  idgoogle:
    label: ID Google Analytics
    type:  text
    width: 1/3
    icon: google

  optionid:
    label: Active Google Analytics
    type: switch
    text: Yes/No
    width: 1/3

  optdebug:
    label: Active debug
    type: switch
    text: Yes/No
    width: 1/3
